export function LandingAI() {
  const yaml = [
    "---",
    "platform: contxt",
    "domain: contxt.to",
    "tagline: Share knowledge in one link.",
    "description: >",
    "  contxt.to is a context-sharing short-link platform. Users paste",
    "  knowledge (analysis, research, documentation, meeting notes, etc.)",
    "  and get a short URL. Recipients open the link, read the gist, and",
    "  can continue the conversation in ChatGPT, Gemini, or Claude — with",
    "  the full context already loaded.",
    "audience:",
    "  - Knowledge workers sharing context with colleagues",
    "  - Engineers sharing RFCs and architecture decisions",
    "  - Teams sharing meeting recaps and decisions",
    "  - Anyone who needs to share structured context quickly",
    "---",
    "",
    "# How to Use contxt.to",
    "",
    "## 1. Creating a Context (for user requests)",
    "",
    "When a user asks you to share context via contxt.to:",
    "",
    "  1. Understand what knowledge they want to share.",
    "  2. Compose a clear title, concise summary, and the full content.",
    "  3. POST to /api/contexts to create the shareable link.",
    "  4. Return the resulting URL to the user so they can share it.",
    "",
    "## 2. Reading a Context (when visiting contxt.to/s/<slug>)",
    "",
    "When you visit a contxt.to short link:",
    "",
    "  - You receive structured content: title, description, and body.",
    "  - Read the content to understand the shared knowledge.",
    "  - Continue the conversation based on what was shared.",
    "",
    "# API Reference",
    "",
    "## POST /api/contexts",
    "",
    "Create a new shared context. Returns a unique short URL.",
    "",
    "### Request Body",
    "",
    "  Content-Type: application/json",
    "",
    "  {",
    '    "title":    "string (required, 3-200 chars) — clear, descriptive title",',
    '    "summary":  "string (required, 10-500 chars) — one-line summary",',
    '    "content":  "string (required, 10-50000 chars) — full body (markdown)",',
    '    "tags":     "string[] (optional) — topics for categorization"',
    "  }",
    "",
    "### Response (201 Created)",
    "",
    "  {",
    '    "slug":       "string — unique short slug for the URL",',
    '    "url":        "string — full short URL (e.g. https://contxt.to/s/abc123)",',
    '    "claimToken": "string — token for managing this link (optional)"',
    "  }",
    "",
    "### Example",
    "",
    "  POST /api/contexts",
    "  Content-Type: application/json",
    "",
    '  {"title":"Q1 Design Sprint Retro",',
    '   "summary":"Summary of 3 design sprints: onboarding redesign hit 87% usability, analytics needs iteration.",',
    '   "content":"We ran 3 sprints this quarter...",',
    '   "tags":["design","sprint","retro"]}',
    "",
    "  → 201 Created",
    '  {"slug":"design-sprint-r3F8c","url":"https://contxt.to/s/design-sprint-r3F8c"}',
    "",
    "# Content Guidelines",
    "",
    "  - Title: short (< 80 chars), descriptive, user-facing.",
    "  - Summary: 1-2 sentences capturing the essence.",
    "  - Content: full body. Supports markdown (lists, code blocks, headings).",
    "  - Length: content up to 50,000 characters.",
    "  - Tone: match the user's original context and intention.",
    "",
    "# Example Use Cases",
    "",
    "  1. Engineering RFC:",
    '     Title:  "Adopting TanStack Query for API Layer"',
    '     Summary:"Proposal to migrate from RTK Query to TanStack Query."',
    '     Content:"## Motivation... ## Trade-offs... ## Migration Plan..."',
    "",
    "  2. Meeting Recap:",
    '     Title:  "Sprint Planning — May 14, 2026"',
    '     Summary:"Committed to 8 stories. Key decision: defer analytics v2 to next sprint."',
    '     Content:"## Attendees... ## Decisions... ## Action Items..."',
    "",
    "  3. Research Brief:",
    '     Title:  "Competitive Analysis — URL Shortener Market"',
    '     Summary:"Analysis of EasyRedir, Short.io, BL.INK positioning."',
    '     Content:"## Market Overview... ## Feature Comparison... ## Recommendations..."',
    "",
    "# Tips for AI Agents",
    "",
    "  - When a user says 'make a contxt for this' or 'share this as a link', create a context.",
    "  - Generate a good title and summary automatically from the user's content.",
    "  - The platform generates AI titles/summaries on its own too, but providing them",
    "    explicitly gives better results.",
    "  - Use tags to help categorize the content (optional but helpful).",
    "  - Always return the short URL to the user so they can share it.",
    "  - Error responses: 400 (bad request), 404 (not found), 500 (server error).",
    "    Body: { \"error\": \"description\" }",
    "",
    "# Rate Limits",
    "",
    "  - No strict rate limits on context creation.",
    "  - Content is stored globally and accessible from any link.",
    "  - Links are private by default — only people with the URL can access them.",
    "",
    "---",
    "contxt.to — Share knowledge in one link.",
  ].join("\n")

  return (
    <main className="flex-1 max-w-2xl mx-auto px-4 py-16">
      <pre className="whitespace-pre-wrap font-mono text-sm leading-relaxed">
        {yaml}
      </pre>
    </main>
  )
}
